name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build library
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Build library
      run: cargo build

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Run tests
      run: cargo test

  clippy:
    name: Run clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: "clippy"
    - name: Run clippy
      run: cargo clippy -- -D warnings

  fmt:
    name: Run rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: "rustfmt"
    - name: Run rustfmt
      run: cargo fmt -- --check
